version: '3.3'

networks:
  final_test:
    external: true

services:
  dbt-deps:
    container_name: dbt-deps
    image: final-project/dbt
    networks:
      - final_test
    volumes:
      - ../../data_build_tools/dbt:/app/dbt
    entrypoint: ["dbt"]
    command: ["deps"]
    env_file:
      - ../../.env

  dbt-run:
    container_name: ${DBT_CONTAINER_NAME}
    image: final-project/dbt
    networks:
      - final_test
    volumes:
      - ../../data_build_tools/dbt:/app/dbt
    entrypoint: ["dbt"]
    command: ["run"]
    depends_on:
      - dbt-deps
    env_file:
      - ../../.env

  dbt-docs:
    container_name: ${DBT_DOCS_CONTAINER_NAME}
    image: final-project/dbt
    volumes:
      - ../../data_build_tools/dbt:/app/dbt
    working_dir: /app/dbt
    networks:
      - final_test
    entrypoint: ["dbt"]
    command: ["docs", "serve"]
    ports:
      - "${DBT_DOCS_PORT}:8000"
    depends_on:
      - dbt-run
    env_file:
      - ../../.env
