project_card_transaction:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('POSTGRES_CONTAINER_NAME') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB_WH') }}"
      schema: public


