version: '3.3'

services:
  minio:
    container_name: ${MINIO_CONTAINER_NAME}
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=${MINIO_USERNAME}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"
    volumes:
      - ../../minio-data:/data
    networks:
      - final_test
    command: server /data --console-address ":9001"

networks:
  final_test:
    external: true