version: '3.3'

services:
  postgres:
    image: postgres:11
    container_name: ${POSTGRES_CONTAINER_NAME}
    hostname: ${POSTGRES_CONTAINER_NAME}
    networks:
      - final_test
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../../postgres/sql:/sql
      - ../../postgres/data:/data
    ports:
      - ${POSTGRES_PORT}:5432

networks:
  final_test:
    external: true
